#include "lexer.h"
#include "unordered_map"
#include "token_name_map.h"

using namespace std;

const unordered_map<string, TokenCode> tokenMap = {
    {"var", tokenVar},
    {"type", tokenType},
    {"routine", tokenRoutine},
    {"is", tokenIs},
    {"integer", tokenInteger},
    {"real", tokenReal},
    {"boolean", tokenBoolean},
    {"record", tokenRecord},
    {"array", tokenArray},
    {"while", tokenWhile},
    {"loop", tokenLoop},
    {"for", tokenFor},
    {"in", tokenIn},
    {"reverse", tokenReverse},
    {"if", tokenIf},
    {"then", tokenThen},
    {"else", tokenElse},
    {"print", tokenPrint},
    {"return", tokenReturn},
    {"end", tokenEnd},
    {"and", tokenAnd},
    {"or", tokenOr},
    {"xor", tokenXor},
    {"not", tokenNot},
    {"true", tokenTrue},
    {"false", tokenFalse}
};

const unordered_map<TokenCode, string> nameMap = {
    {tokenVar, "var"},
    {tokenType, "type"},
    {tokenRoutine, "routine"},
    {tokenIs, "is"},
    {tokenInteger, "integer"},
    {tokenReal, "real"},
    {tokenBoolean, "boolean"},
    {tokenRecord, "record"},
    {tokenArray, "array"},
    {tokenWhile, "while"},
    {tokenLoop, "loop"},
    {tokenFor, "for"},
    {tokenIn, "in"},
    {tokenReverse, "reverse"},
    {tokenIf, "if"},
    {tokenThen, "then"},
    {tokenElse, "else"},
    {tokenPrint, "print"},
    {tokenReturn, "return"},
    {tokenEnd, "end"},
    {tokenAnd, "and"},
    {tokenOr, "or"},
    {tokenXor, "xor"},
    {tokenNot, "not"},
    {tokenTrue, "true"},
    {tokenFalse, "false"},
    {tokenAssign, ":="},
    {tokenDotDot, ".."},
    {tokenArrow, "=>"},
    {tokenLessEqual, "<="},
    {tokenGreaterEqual, ">="},
    {tokenNotEqual, "/="},
    {tokenLess, "<"},
    {tokenGreater, ">"},
    {tokenEqual, "="},
    {tokenPlus, "+"},
    {tokenMinus, "-"},
    {tokenStar, "*"},
    {tokenSlash, "/"},
    {tokenPercent, "%"},
    {tokenDot, "."},
    {tokenComma, ","},
    {tokenSemicolon, ";"},
    {tokenColon, ":"},
    {tokenLeftParen, "("},
    {tokenRightParen, ")"},
    {tokenLeftBracket, "["},
    {tokenRightBracket, "]"},
    {tokenIdentifier, "identifier"},
    {tokenIntegerLiteral, "integer literal"},
    {tokenRealLiteral, "real literal"},
    {tokenNewline, "end of line"},
    {tokenEOF, "end of file"},
    {tokenUnknown, "invalid token"}
};
